version: '3.9'
services:
   app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: kavita_server_1
      APP_PORT: 3000
    server:
        image: kizaing/kavita:latest
        volumes:
            - ./manga:/manga
            - ./data:/kavita/config
        user: "1000:1000"
        init: true
